server :
  port : 5000

app :
  version : "1.0.0"

spring :
  datasource :
    url : ${DB_URL}
    username : ${DB_USER}
    password : ${DB_PASSWORD}
  jpa :
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : none
      show-sql : true
keycloak:
  realm: MyDemo
  auth-server-url : http://127.0.0.1:8080/auth
  ssl-required : external
  resource : api
  public-client: false
  credentials:
    secret : 0b061108-9a26-4c86-9758-722f552774ea
  bearer-only: true
  security-constraints[0]:
    security-collections[0]:
      patterns[0]: /covidalert/api/*
    securityCollections[0]:
      methods[0]: GET
      methods[1]: PUT
      methods[2]: DELETE
      methods[3]: PATCH
